language: android
jdk: openjdk10
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./gradlew assembleRelease